version: '3'
services:
  server:
    image: arnulfosolis/simple-pos
    environment:
        DB_PASSWORD: simple_pos
    depends_on:
      - db
    expose:
      - "5000"
    ports:
      - 5000:5000
    networks:
      - local
  db:
    image: postgres:10
    expose:
      - "5432"
    restart: on-failure
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: simple_pos
      POSTGRES_USER: pos_user
      POSTGRES_DB: business
    networks:
      - local
    volumes:
      - db:/var/lib/postgresql/data

networks:
  local:

volumes:
  db:
